language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true

before_script:
  - git checkout master
  - composer self-update && composer install

script: bin/kahlan --coverage=3 --scrutinizer="export.xml"

after_script:
  - if [ $(phpenv version-name) = "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ $(phpenv version-name) = "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover "export.xml"; fi