#!/usr/bin/env php
<?php

$kahlan = 'https://raw.githubusercontent.com/crysalead/kahlan/master/composer.json';
$filterVersion = json_decode(file_get_contents($kahlan), true)['require']['crysalead/filter'];

`COMPOSER_ROOT_VERSION={$filterVersion} composer install`;
